export default {
  generatorMessage: 'This page is generated by the generator',
  componentMessage: 'This component is generated by the generator',
  welcome: 'Welcome to use generator to generate your file',
  footer: 'react-native-boilerplate',
  // 以上为测试翻译的翻译代码

  // EntryScene
  takeLook: '先去转转',
  login: '登录',
  signUp: '注册',
};
